### ISSUE TITLE
test remove vpool did not detect that it no longer works

### ISSUE THREAD

**Issue by domsj** [openvstorage/integrationtests#253]
https://github.com/openvstorage/framework/issues/653 was not detected by the relevant test.
Apparently this is due to the tests not setting a storage ip (different from localhost).
The tests should reflect as closely as possible how the code will actually be run by setting a different storage ip, which would've detected this issue sooner.

**Comment by pploegaert** [comment]
CLOSED: covered by scenario's functionality
vpool api receives:
"connection_info": {"host": "", "port": "", "client_id": "", "client_secret": ""},
"storage_ip": vpool_details['storage_ip'],
"storagerouter_ip": storagerouter_ip,
...
