### ISSUE TITLE
Package/Integrate healthcheck in autotest runs

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#274]
- packaging
  -- keep naming convention similar to other ovs packages
  -- transfer packaging dir from another repo, e.g. framework
  -- update files accordingly
  -- create PR when ready + review by me/Kenneth
- update jenkins to include packaging for healthcheck
  http://10.100.129.100:8080/view/Packaging/job/openvstorage-packaging/
- use silent
- run:
  -- as first step
  -- at the end of arakoon/backend/vdisk/vmachine/vpool tests
  -- as final step

**Comment by kinvaris** [comment]
For packaging the healthcheck also see https://github.com/openvstorage/openvstorage-health-check/issues/71

**Comment by JeffreyDevloo** [comment]
Healthcheck can be packaged and has been integrated in an autotest: https://github.com/openvstorage/integrationtests/pull/362
