### ISSUE TITLE
Add autotest to validate add/append/reduce/remove roles on disk

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#281]
Use/Add methods in general_disk to:
- add a role to a disk
- append a role to exisiting roles on a disk
- remove 1 role from existing roles (leaving at least 1 role behind)
- remove all roles

For each test validate pre/post conditions

Add test to e.g. disklayout/disk_roles_test.py

**Comment by JeffreyDevloo** [comment]
openvstorage-test-2.7.2-rev.993.c9deb7b
