### ISSUE TITLE
Add autotest to validate node removal/addition

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#284]
Scenario:
- setup 3 node env or use NB env
- deploy backend/vpool/vms across all nodes
- start vms running an ubuntu os
- remove one node
- verify all services are running / reconfiguration is correct (be thorough about this)
- remove a second node
- verify all services are running / reconfiguration is correct (be thorough about this)
- add both nodes
- verify all services are running / reconfiguration is correct (be thorough about this)

1st step: verify manually
2nd step: automate

**Comment by JeffreyDevloo** [comment]
The manual test cases revealed alot of issues on topic.
They have been fixed by now and a autotest could be implemented to keep testing these cases.

**Comment by JeffreyDevloo** [comment]
Also: https://github.com/openvstorage/integrationtests/issues/273 is a duplicate of this issue.

**Comment by pploegaert** [comment]
CLOSED: duplicate of #273
