### ISSUE TITLE
Add autotest to validate power outage of one/more nodes

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#287]
1/ Initially perform these test manually - to get a quick view on the stability
2/ As a next step we can use Bert's qemu type of install to setup vms via ansible on ovs via edge,
so we can also automate the shutdown/startup of these vms ...

Setup:
- setup 3 node env or use NB env
- deploy backend/vpool/vms across all nodes
- start vms running an ubuntu os

Scenario 1:
- open up gui on node 3
- poweroff one node 3
- verify we can still use gui interface (should redirect to another node - requires accepting certificate again)
- poweron node 3
- verify no issues occur on node 3 / other nodes
- verify we can still use gui interface
- verify we can again use gui interface on node 3

Scenario 2:
- poweroff all nodes simultaneously
- poweron all nodes
- verify all components are operational by starting up de vms again

Use your own creativity to figure out more test scenario's if you think sth is missing :)

**Comment by JeffreyDevloo** [comment]
All of the HA tests are currently incorporating a form of power loss.
