### ISSUE TITLE
disk_roles_test suite leaves /mnt/hddx mounted + partitions present - pls cleanup after test

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#334]
as described

**Comment by JeffreyDevloo** [comment]
To do:

- [ ] Cleanup mointpoint

- [ ] Remove the created partition

**Comment by pploegaert** [comment]
PASSED: http://testrail.openvstorage.com/index.php?/plans/view/34965

![at-334](https://cloud.githubusercontent.com/assets/8393135/20620683/2de20478-b2fb-11e6-891b-b953cc619e28.png)
