### ISSUE TITLE
[merge-revamped] Change AlbaCli back to framework

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/integrationtests#363]
### Problem description
Not all Alba commands support --to-json. The AlbaCli wrapper adds this option by default so we had to implement our own adaptation for this wrapper (modified one from framework).
To stay up to date, we must change our adaptation back to the one of the framework.

Waiting for https://github.com/openvstorage/alba/issues/473

**Comment by pploegaert** [comment]
Latest alba_1.2.3 is now available on unstable - it should incorporate required changes - pls validate if ok

**Comment by JeffreyDevloo** [comment]
Did not implement a different version in autotests as none of our tests relied on AlbaCLI.

**Comment by toolslive** [comment]
hold on:
the latest request for even more commands (https://github.com/openvstorage/alba/issues/477 ) 
which resulted in https://github.com/openvstorage/alba/pull/480
is not in this release. It will come in 1.3

**Comment by JeffreyDevloo** [comment]
Yes but this ticket was irrelevant either way. The Healthcheck uses their own AlbaCli now to work around the missing --to-json options.
This repository doesn't.
