### ISSUE TITLE
Add DTL autotests

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/integrationtests#426]
Test possible DTL configuration with a single or multiple storagedrivers in a vpool:

BASIC: https://github.com/openvstorage/integrationtests/commit/5b3d30e55e1ad9d1024e4e7898c84dd131ba05bb

- ~~Configuring a DTL with only 1 storagedriver to a non existing location (should fail scenario)~~; **blocked by** https://github.com/openvstorage/framework/issues/1417
- ~~Configuring a DTL with 2 storagedrivers~~
- ~~When deploying a vdisk, the DTL should be configured in the primary or recovery DC based on choice: security or speed?~~
- ~~Shutting down a node with a vdisk with sync DTL will be testing in the HA autotests~~; **tested by** #427 

ADVANCED:

- Shutting down a proxy, writing some data to the vdisk, starting the proxy again, trigger volumedriver `restart_from_dtl`, checking if the written data on the vdisk is still present. **(currently only works in the same datacenter only)**

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/integrationtests/pull/460
