### ISSUE TITLE
Add HA autotests

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/integrationtests#427]
Test will require the parent hypervisor information for the first tests. These can be modified by killing certain processes later
Flow:
- Find sync dtl vpool
- Get two storagerouter
- Determine which will get shot and which will survive (requires 3node setup)
- Create a VM on a computenode (a third node which is not involved)
- Start writing (to filesystem on the VM)
- Shoot the storagerouter
- Validate the Edge Connection, validate IOPS downtime, validate io errors

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/integrationtests/pull/442
