### ISSUE TITLE
Check dynamic log levels of each component

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/integrationtests#428]
Can you find out which component have a dynamic log level property?

**Comment by wimpers** [comment]
For the framework components this is dynamic  (https://github.com/openvstorage/ovs-documentation/issues/71). 

To be checked what about ALBA and VolDrv.

**Comment by wimpers** [comment]
@jeroenmaelbrancke why was this created in integration tests? Should this be moved to devops?

**Comment by jeroenmaelbrancke** [comment]
@wimpers i think you can move this to devops. No idea why i created this ticket on the integrationtests repo.
