### ISSUE TITLE
(Re)move setup.json + Workflow to setups repo

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#432]
Specific setup.json files are located in setups repo anyway.
Worker class can be moved there too as a specific setup.json gets copied to the qa env during test setup.

Installation impact on nightly build should be minor

**Comment by JeffreyDevloo** [comment]
- https://github.com/openvstorage/integrationtests/pull/459
- https://github.com/openvstorage/automation-lib
