### ISSUE TITLE
API validation - volumedriver refreshConfiguration

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#440]
api.post('storagedrivers/<SR.GUID>/refresh_configuration')
Related:
https://github.com/openvstorage/framework/issues/1239

**Comment by JeffreyDevloo** [comment]
Adding won't fix as I do not see the immediate benefit of such a check.

**Comment by kvanhijf** [comment]
@JeffreyDevloo : Do we have a test validating this API call already?  Cause i hope we do test every API available?
