### ISSUE TITLE
Regression test: fast read after write

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/integrationtests#468]
In continuation of:
* https://github.com/openvstorage/volumedriver/issues/283
* https://github.com/openvstorage/volumedriver/commit/9a5a49e88a5ea2b5da7b9f7296a9fa51d3389cdf
* https://github.com/openvstorage/org_quality/issues/41

We will write a test that uses vdbench to reproduce this issue.

vdbench is present here: http://fileserver.cloudfounders.com/Operations/IT/Software/vdbench/vdbench.zip

When installing vdbench on a ubuntu 16.04. Follow the following steps:
* `apt-get install openjdk-9-jre-headless`
* Create a config file with details: `test.cfg`
```
data_errors=1
sd=sd1,lun=/root/redlicha/vdbench/testfile.bin,threads=4,size=3g
wd=wd1,sd=(sd1),xfersize=(4k,25.68,8k,26.31,16k,6.4,32k,7.52,60k,10.52,128k,9.82,252k,7.31,504k,6.19,984k,0.23,1032k,0.02),rdpct=50,seekpct=100,openflags=directio
rd=run1,wd=wd1,iorate=max,elapsed=7200,interval=1
``` 
* Execute: `./vdbench -vr -f test.cfg`

**REMARKS:** Spotting a failure can take up to 2 - 4 hours.

**Comment by JeffreyDevloo** [comment]
Fixed by: https://github.com/openvstorage/integrationtests/pull/499
Waiting for approval
