### ISSUE TITLE
Add vdbench test

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#484]
Investigate if this could trigger addtional issues.

Also take data validation into account when testing with vdbench:
e.g. -vr -j

-v Activate data validation.
-vr Activate data validation, immediately re-read after each write.
-vw Activate data validation, but don’t read before write.
-vt Activate data validation, keep track of each write timestamp (memory
intensive)
-j Activate data validation

**Comment by JeffreyDevloo** [comment]
Looks like this a duplicate to: https://github.com/openvstorage/integrationtests/issues/468
