### ISSUE TITLE
Update scrubber scenario to start without snapshots as described

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#485]
Scenario:

1/ disable automatic snapshots
2/ create vdisk
3/ write a lot of data on that disk
4/ run scrubber - no action will be performed + verify
5/ create snapshot1
6/ write some more data +- 100MB
7/ create snapshot2
8/ delete snapshot 1
9/ run scrubber + verify old data is gone

**Comment by JeffreyDevloo** [comment]
So https://github.com/openvstorage/integrationtests/blob/master/ci/scenarios/vmachine/check_scrubbing_test/main.py ... ?
