### ISSUE TITLE
Add block cache support for autotests during add vpool

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#512]
### Cover area
- framework

// What type of functionality was used
- block cache support

// Which type of issue is this
- new feature

### User story
// Describe the user story/scenario here.
<---------------------------------------------------------->

### Problem that arose
http://10.100.199.200:8080/job/Configure_OVS_environment/477/console

#### Log
00:02:24 TASK [execute integration-tests] ***********************************************
00:02:24 Friday 28 April 2017  00:02:24 +0200 (0:00:00.417)       0:05:03.137 ********** 
00:15:42 fatal: [ctrl01]: FAILED! => {"changed": true, "cmd": "python -c \"import sys, os; sys.path.append('/opt/OpenvStorage'); os.environ['OVS_LOGTYPE_OVERRIDE'] = 'file'; from ci.main import Workflow; Workflow.main()\"", "delta": "0:13:17.268033", "end": "2017-04-28 00:15:42.226077", "failed": true, "rc": 1, "start": "2017-04-28 00:02:24.958044", "stderr": "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"/opt/OpenvStorage/ci/main.py\", line 315, in main\n    w.run()\n  File \"/opt/OpenvStorage/ci/main.py\", line 73, in run\n    Workflow._run_with_retry(self.setup, self.config['ci']['setup_retries'])\n  File \"/opt/OpenvStorage/ci/main.py\", line 63, in _run_with_retry\n    target(*args, **kwargs)\n  File \"/opt/OpenvStorage/ci/main.py\", line 235, in setup\n    VPoolSetup.add_vpool(vpool_name=vpool_name, vpool_details=vpool_details, api=self.api, albabackend_name=albabackends, storagerouter_ip=storagerouter_ip, proxy_amount=proxy_amount)\n  File \"/opt/OpenvStorage/ci/api_lib/validate/decorators.py\", line 228, in validate\n    return func(*args, **kwargs)\n  File \"/opt/OpenvStorage/ci/api_lib/validate/decorators.py\", line 82, in validate\n    return func(*args, **kwargs)\n  File \"/opt/OpenvStorage/ci/api_lib/validate/decorators.py\", line 56, in validate\n    return func(*args, **kwargs)\n  File \"/opt/OpenvStorage/ci/api_lib/setup/vpool.py\", line 108, in add_vpool\n    raise RuntimeError(error_msg)\nRuntimeError: vPool myvpool01 has failed to create on storagerouter 10.100.188.33 because: \nMissing required param \"block_cache_on_read\" in actual parameters\nMissing required param \"block_cache_on_write\" in actual parameters", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/integrationtests/pull/515

**Comment by pploegaert** [comment]
PASSED:
http://testrail.openvstorage.com/index.php?/tests/view/1219727&group_by=cases:section_id&group_order=asc&group_id=29867
