### ISSUE TITLE
Cleanup vm + vdisks for related autotests due to limited disk space on virtual envs

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#533]
Test results might get affected by remaining vms + their vdisks of previous tests still residing on the environment especially on virtual envs with limited asd disk space.

Please by default remove these disks we can always disable the cleanup when debugging a specific data content related isse

### Problem that arose
Additional tests might fail due to full asd devices

### Setup
Occurs mainly on virtual test environments with limited asds sizes of 5GB

**Comment by JeffreyDevloo** [comment]
Will be fixed by: https://github.com/openvstorage/integrationtests/pulls
