### ISSUE TITLE
Failed test: add_remove_alba_vpool_test

### ISSUE THREAD

**Issue by jake9050** [openvstorage/integrationtests#581]
This night's builds started throwing these for this test on both of the unstable envs:

EE-PHY-3N-187.31-unstable - http://testrail.openvstorage.com/index.php?/plans/view/38378
EE-VIR-3N-199.181-unstable - http://testrail.openvstorage.com/index.php?/plans/view/38374

`Removal of preset 'ciaddremovevpool' for backend 'mybackend' failed with 'Albamgr exception(Albamgr_protocol.Protocol.Error.Unknown,Protocol_common.XException(4, "/alba/preset/propagation/ciaddremovevpool"))'`

Most likely related to https://github.com/openvstorage/integrationtests/issues/556

**Comment by JeffreyDevloo** [comment]
Very much related to #556 in the sense that it's the same issue.
```
Removal of preset 'ciaddremovevpool' for backend 'mybackend02' failed with 'Albamgr exception(Albamgr_protocol.Protocol.Error.Unknown,Protocol_common.XException(4, "/alba/preset/propagation/ciaddremovevpool"))'
```
