### ISSUE TITLE
Saveguard logs for a week

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/integrationtests#593]
All log files(systemd and others) should be retained longer than the last hour.
Rate limiting should also be disabled.
Currently we loose all evidence which makes it hard to investigate failed test cases.
Remote syslog is definitely an option.

**Comment by jeroenmaelbrancke** [comment]
Solved in the setup repo: https://github.com/openvstorage/setups/pull/79

added a rsyslog server for the test environments.
