### ISSUE TITLE
new Toolbox location

### ISSUE THREAD

**Issue by simonOpenV** [openvstorage/integrationtests#615]
Some usage of the integration tests and automation lib still use the old verify_required_params of the toolbox. These old usages should be changed to the new path of the Extensionstoolbox.verify_required_params

**Comment by simonOpenV** [comment]
Fixed in #614 , package information : openvstorage-test-3.4.1-dev.1518092945.bc05eb4
and Automation-lib:
Fixed in https://github.com/openvstorage/automation-lib/pull/80
Package information: openvstorage-automation-lib-0.5.0-dev.1518094111.b2d2297

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/integrationtests/releases/tag/3.4.1
Packaged in openvstorage-test_3.4.1-1_amd64.deb
