### ISSUE TITLE
iSCSI integration test coverage

### ISSUE THREAD

**Issue by simonOpenV** [openvstorage/integrationtests#616]
Currently, the ISCSI plugin has little coverage of tests in the framework. 
A test suite in the integrationtests would fix this.

**Comment by simonOpenV** [comment]
Fixed in:
Automation lib: https://github.com/openvstorage/automation-lib/pull/84
Package information: openvstorage-automation-lib-0.5.0-dev.1518105574.c1db9d3
Integration tests: #617
Package information: openvstorage-test-3.4.1-dev.1518106152.3e04fd7

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/integrationtests/releases/tag/3.4.1
Packaged in openvstorage-test_3.4.1-1_amd64.deb
